package com.cztffa.xpath.business;

public class SmbPersonalInfoPageXpath {
    public static final String SELECTIONYES = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-declaration[@t-model='Party__r']//input[@value='Yes']";
    public static final String PROCEEDWITHOUTPREFILLBTN = "//button[normalize-space()='Proceed without prefill']";
    public static final String FIRSTNAME = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='Party__r.FirstName__c']/descendant::input";
    public static final String MIDDLENAME = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='Party__r.MiddleName__c']/descendant::input";
    public static final String LASTNAME = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='Party__r.LastName__c']/descendant::input";
    public static final String DATEOFBIRTH = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-date[@t-model='Party__r.BirthDate__c']//input";
    public static final String CITIZENSHIP = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='Party__r.Citizenship__c']/descendant::input";
    public static final String CITIZENSHIPCITIZENOPTAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Citizen')]";
    public static final String CITIZENSHIPALIENAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Permanent Resident Alien')]";
    public static final String CITIZENSHIPCOUNTRY = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='Party__r.CountryOfCitizenship__c']//input";
    public static final String CITIZENSHIPCOUNTRYAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Albania')]";
    public static final String WILLINGFOREIGN = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='Party__r.CZAffiliatedWithForeignGoverment__c']//input";
    public static final String WILLINGFREIGNAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Yes')]";
    public static final String STREETADDRESS1 = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-address[@t-model='Party__r.AddressXrefs__r.0.Address__r']//tf-input[@t-model='Line1__c']/descendant::input";
    public static final String ADDRESSTEXT = "(//div[contains(text(),'%s')])[1]";
    public static final String CITY = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='City__c']//input";
    public static final String STATE = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='State__c']/descendant::input";
    public static final String STATEOPTAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Arizona')]";
    public static final String ZIP = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='ZipCode__c']//input";
    public static final String PREFFEREDCONTACT = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='Party__r.PreferredContactMethod__c']/descendant::input";
    public static final String PREFERREDCONTACTMOBILEAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Mobile Phone')]";
    public static final String MOBILEPHONE = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-phone[@t-model='Party__r.PrimaryPhone__c']//input";
    public static final String EMAIL = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-email[@t-model='Party__r.PrimaryEmail__c']//input";
    public static final String EMPLOYMENT = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='Party__r.Employments__r.0.Type__c']/descendant::input";
    public static final String EMPLOYMENTEMPLOYEDAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Employed')]";
    public static final String EMPLOYER = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='Party__r.Employments__r.0.EmployerName__c']//input";
    public static final String OCCUPATION = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-ssn[@t-model='Party__r.NationalIdentifierValue__c']//input";
    public static final String SSN = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-ssn[@t-model='Party__r.NationalIdentifierValue__c']//input";
    public static final String IDTYPE = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='Type__c']/descendant::input";
    public static final String IDNUMBER = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='IdentificationNumber__c']//input";
    public static final String SECURITYWORD = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-input[@t-model='Party__r.CZSecurityWord__c']//input";
    public static final String ISSUEDATE = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-date[@t-model='IssueDate__c']//input";
    public static final String EXPIRYDATE = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-date[@t-model='ExpirationDate__c']//input";
    public static final String STATEISSUED = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='IssuingState__c']//input";
    public static final String COUNTRYISSUED = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='IssuingCountry__c']//input";
    public static final String SELECTRELATION = "//tf-expansion-panel[@t-model='Submission__c.PartyXrefs__r.%s']//tf-dropdown[@t-model='RelationCode__c']//input";
    public static final String GETRELATIONIONSHIPOFPERSON = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'%s')]";
    public static final String IDTYPEMILITARYAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Military')]";
    public static final String IDTYPEDRIVERLICENCEAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Drivers License')]";
    public static final String IDTYPESTATEIDAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'State ID')]";
    public static final String IDTYPEPASSPORTAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Passport')]";
    public static final String IDTYPERESIDENTALIENAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Resident Alien Card')]";
    public static final String PERSONALINFONEXTBUTON = "//button[@class='btn btn-primary float-end tf-step-action-next']";
    public static final String ADDADDITIONALAPPLICANTBUTTON = "//button[normalize-space()='Add a Person']";
    public static final String STATEAPPLY = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Alaska')]";
    public static final String SECURITYWORDERROR = "//small[contains(text(),'Security Word')]";
    public static final String SSNERROR = "//small[contains(text(),'Social Security Number')]";
    public static final String RELATIONSELECT = "//div[@class='dropdown-item ng-star-inserted'][contains(text(),'Owner')]";
    public static final String PERCENTAGE = "//input[@type='text' and @inputmode='decimal' and @class='form-control']";
}
